[package]
name = 'projectRbindings'
publish = false
version = '0.1.0'
edition = '2021'
rust-version = '1.65'

[lib]
crate-type = [ 'staticlib' ]
name = 'projectRbindings'

[dependencies]
extendr-api = '0.8.0'
project_with_bindings = { path = "../../../rust/" }